### ISSUE TITLE
[FE, BE] Orders

### ISSUE THREAD

**Issue by hejsekvojtech** [bouraci/wea_be#21]
Tabulka s objednávkama

- id uživatele
- množství
- stav (jak se budou stavy měnit, tak to nevím, asi udělám na FE spešl godmode stránku kde budu moct stav objednávky měnit - GET a POST endpoint pro godmode co bude dávat basic info a měnit stav)
- cena (ani nevíme jak data z CDB vypadaj ffs.)
- datum

Pouze pro přihlášené uživatele

není finální

**Comment by VojtechGero** [comment]
udělat aby nešlo obědnat knihy co sou hidden

**Comment by VojtechGero** [comment]
done
